baseURL = "https://DenzelPenzel.github.io/blog/"
languageCode = "en-us"
title = "Denzel's research notes"
theme = "m10c"

[params]
  author = "Denzel"
  description = "This blog is where I share my thoughts and findings from my research"
  avatar = "/img//avatars/me.jpg"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/DenzelPenzel"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/denzel_penzel"